[package]
authors = ["Praveen Perera <praveen@avencera.com>"]
edition = "2021"
license = "Apache-2.0"
name = "rustywind"
version = "0.15.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cli
clap = {version = "3.1", features = ["cargo", "derive"]}
indoc = "1.0"

# files
ignore = "0.4"

# utils
itertools = "0.10"
once_cell = "1.9"

# string matching
aho-corasick = "0.7"
regex = "1"

# logging
env_logger = "0.9"
log = "0.4"

# parallel
rayon = "1.5"

# errors
color-eyre = "0.6"
eyre = "0.6"

# json parsing
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.59"

[dev-dependencies]
pretty_assertions = "1.0"

[profile.release]
lto = true
